import glob
import os
import pathlib
import setuptools
import sys

install_requires = []
tests_require = []
dev_requires = install_requires + tests_require + ["documenteer[pipelines]"]
tools_path = pathlib.Path(setuptools.__path__[0])
base_prefix = pathlib.Path(sys.base_prefix)
data_files_path = tools_path.relative_to(base_prefix).parents[1]
config_files = glob.glob("config/*")

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="ts_ddsconfig",
    description="OpenSplice configuration files for Vera Rubin observatory control system.",
    # install_requires=install_requires,
    package_dir={"": "python"},
    use_scm_version={
        "write_to": "python/lsst/ts/ddsconfig/version.py",
        "write_to_template": scm_version_template,
    },
    packages=setuptools.find_namespace_packages(where="python"),
    data_files=[
        (os.path.join(data_files_path, "qos"), ["qos/QoS.xml"]),
        (os.path.join(data_files_path, "config"), config_files),
    ],
    include_package_data=True,
    # scripts=[],
    # tests_require=tests_require,
    extras_require={"dev": dev_requires},
    license="GPL",
    project_url={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_ddsconfig",
    },
)
