{% set data= load_setup_py_data() %}
package:
  name: ts-ddsconfig
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build
  source_files:
    - python
    - tests
    - qos
    - config
    - setup.cfg

  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - setuptools
    - setuptools_scm
