{% set data= load_setup_py_data() %}
package:
  name: ts-ddsconfig
  version: {{ data.get('version') }}

source:
  path: ../

build:
  skip: False #[win]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - setuptools
    - setuptools_scm
